name: shelf_graphql
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/Flutterando/shelf_graphql

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  path: ^1.8.2
  shelf: ^1.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
